#!/usr/bin/env sh

file_path() {
  path=""
  for arg in "$@"; do
    path="$path${path:+/}$arg"
  done

  case "$path" in
    /*) ;;

    *)
      path="$D/$path"
      ;;
  esac

  realpath -ms "$path"
}

file_link() {
  case "$1" in /*) source="$1" ;; *) source="$(realpath -ms "$W/$1")" ;; esac
  target="$(file_path "${2:-${1##*/}}")"

  if [ -d "$target" ]; then
    target="$target/${1##*/}"
  fi

  case "$target" in
    $D*)
      mkdir -p "${target%/*}"

      if [ ! -e "$target" ] && [ ! -h "$target" ]; then
        debug "creating link: $target -> $source"
        ln -s "$source" "$target"
      else
        link=$(readlink -s "$target")
        if [ "$link" = "$source" ]; then
          debug "$target already installed (skipping)"
          true
        elif [ "$link" = '' ]; then
          warn "$target already exists"
          false
        else
          warn "$target already exists and links to $link"
          false
        fi
      fi
      ;;

    *)
      error "$target is forbidden as it is outside $D"
      false
      ;;
  esac
}

file_unlink() {
  target="$(file_path "$*")"

  case "$target" in
    $D*)
      if [ -e "$target" ]; then
        rm -rf "$target"

        parent="${target%/*}"
        if [ "$D" != "$parent" ] && [ -e "$parent" ]; then
          file_unlink "$parent"
        fi
      else
        warn "$target not found"
      fi
      ;;
    *)
      error "$target is forbidden as it is outside $D"
      false
      ;;
  esac
}
