#!/usr/bin/env sh
# shellcheck disable=SC1090 disable=SC1091
#
# $1 - action
# $2 - package folder
set -o errexit  # exit on command failure
set -o nounset  # exit on undeclared variable usage

if [ "$DOTFILES_TRACE" -gt 0 ]; then
  set -o xtrace # enable shell command tracing
fi

ACTION=$1
PKGDIR=$2
BASEDIR=$(realpath "${0%/*}")
DOTFILES_RUNTIME="$BASEDIR/runtime"
PKGFILE="$PKGDIR/pkgrc"

# common package variables
D="${DOTFILES_PREFIX:-${HOME}}"
W="$PKGDIR"
PN="${PKGDIR##*/}"
export D W PN PREFIX PKGDIR

# initialize runtime
. "$BASEDIR/output.sh"
. "$DOTFILES_RUNTIME/base"

# load package file
cd "$PKGDIR" 2>/dev/null || die "package not found: $PN"
[ -f "$PKGFILE" ] && . "$PKGFILE"

# shellcheck disable=SC2034 ## used by output functions
LOG_PREFIX=" $PN:"

if type "$ACTION" >/dev/null 2>&1; then
  debug "running '$ACTION' action ..."
  "$ACTION"
else
  warn "$ACTION action not supported"
fi
