#!/usr/bin/env sh

import files xdg gen

zsh_add_rc() {
  templates="$(xdg_get_data 'zsh' 'rc.d')"
  source="$1"
  target="${2:-${1##*/}}"

  file_link "$source" "$(file_path "$templates" "$target")"
  gen_file "$(file_path '.zshrc')" "$templates"
}

zsh_del_rc() {
  templates="$(xdg_get_data 'zsh' 'rc.d')"
  target="$(file_path "$templates" "$*")"

  file_unlink "$target"
  gen_file "$(file_path '.zshrc')" "$templates"
}

zsh_add_env() {
  templates="$(xdg_get_data 'zsh' 'env.d')"
  source="$1"
  target="${2:-${1##*/}}"

  file_link "$source" "$(file_path "$templates" "$target")"
  gen_file "$(file_path '.zshenv')" "$templates"
}

zsh_del_env() {
  templates="$(xdg_get_data 'zsh' 'env.d')"
  target="$(file_path "$templates" "$*")"

  file_unlink "$target"
  gen_file "$(file_path '.zshenv')" "$templates"
}

zsh_update_antibody() {
  antibody_bin="$(xdg_get_bin 'antibody')"
  antibody_init="$(xdg_get_cache 'zsh' 'antibody' 'init.zsh')"
  antibody_plugins="$(xdg_get_data 'zsh' 'antibody' 'plugins')"

  if [ ! -e "$antibody_plugins" ]; then
    return 0
  fi

  if [ ! -x "$antibody_bin" ]; then
    info 'installing antibody'
    mkdir -p "${antibody_bin%/*}"
    curl -sfL https://git.io/antibody | sh -s - -b "${antibody_bin%/*}"
  fi

  debug 'updating antibody init script'
  mkdir -p "${antibody_init%/*}"
  "$antibody_bin" bundle < "$antibody_plugins" > "$antibody_init"

  gen_file "$(file_path '.zshrc')" "$templates"
}

zsh_add_plugin() {
  antibody_plugins="$(xdg_get_data 'zsh' 'antibody' 'plugins')"

  mkdir -p "${antibody_plugins%/*}"
  for plugin in "$@"; do
    echo "$plugin" >> "$antibody_plugins"
  done

  zsh_update_antibody
}

zsh_del_plugin() {
  antibody_plugins="$(xdg_get_data 'zsh' 'antibody' 'plugins')"

  if [ ! -e "$antibody_plugins" ]; then
    return 0
  fi

  mkdir -p "${antibody_plugins%/*}"
  temp=$(mktemp)
  for plugin in "$@"; do
    grep -v "$plugin" "$antibody_plugins" > "$temp" \
      && mv "$temp" "$antibody_plugins"
  done

  zsh_update_antibody
}
