#!/usr/bin/env bash

function link {
  local source="${W:?}/$1"
  local target="${D:?}/$2"

  if [[ -e "$source" ]]; then
    if [[ -L "$target" ]]; then
      local ref=$(readlink "$target")
      if [[ "$ref" = "$source" ]]; then
        debug "linked $target -> $source (omitted)"
        return
      else
        warn "$target already exists and point to $ref"
        # TODO: ask to override the file?
        return
      fi
    fi

    debug "linked $target -> $source"
    mkdir -p "${target%/*}"
    ln -s "$source" "$target"
  fi
}

function link_all_deep {
  local base="${W:?}/$1"
  local target="${2:-.}"
  local file_prefix="$3"

  while read -r file; do
    local relative=${file##"$base/"}
    local pkg_relative=${file##"$W/"}
    link "$pkg_relative" "${target:?}/$file_prefix$relative"
  done < <(find "$base" -mindepth 1 -not -type d 2>/dev/null)
}

function unlink {
  local target="$1"
  local full_target="${PREFIX:?}/$target"
  if [[ -e "$full_target" ]]; then

    debug "removed $full_target"
    rm -r "$full_target"

    local parent="${target%/*}"
    local full_parent="${full_target%/*}"
    if [[ "$parent" != '' ]] && [[ "$parent" != '.' ]] && [[ -n "$(find "$full_parent" -maxdepth 0 -type d -empty 2>/dev/null)" ]]; then
      unlink "$parent"
    fi
  fi
}

function unlink_all_deep {
  local base="${W:?}/$1"
  local target="${2:-.}"
  local file_prefix="$3"

  while read -r file; do
    local relative=${file##"$base/"}
    unlink "${target:?}/$file_prefix$relative"
  done < <(find "$base" -mindepth 1 -not -type d 2>/dev/null)
}
